### ISSUE TITLE
UFW pillar data not parsing correctly?

### ISSUE THREAD

**Issue by mikecmpbll** [meritec/ufw-formula#2]
Certain UFW pillar isn't being applied—perhaps not merging correctly if you have multiple definition blocks, e.g. ?:

```yaml
ufw:
  services:
    ssh:
      from_addr:
        - 1.2.3.4
  services:
    ssh:
      from_addr:
        - 5.6.7.8
```
